/*
		Project:		WINEDIT (Windows MDI-Editor)
		Module: 		WINEDIT.H
		Description:	The IDs for the ressource objects
		Author:			Martin Gäckler
		Address:		Hofmannsthalweg 14, A-4030 Linz
		Web:			https://www.gaeckler.at/

		Copyright:		(c) 1995-2026 Martin Gäckler

		This program is free software: you can redistribute it and/or modify  
		it under the terms of the GNU General Public License as published by  
		the Free Software Foundation, version 3.

		You should have received a copy of the GNU General Public License 
		along with this program. If not, see <http://www.gnu.org/licenses/>.

		THIS SOFTWARE IS PROVIDED BY Martin Gäckler, Linz, Austria ``AS IS''
		AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
		TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
		PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR
		CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
		SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
		LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
		USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
		ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
		OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
		OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
		SUCH DAMAGE.
*/

#define EDIT_ICON			101
#define EDIT_ICON_DLG		102
#define WINDOW_MENU			3
#define EDIT_BREAK			666		// this is a marke for an old menu entry
									// I want to re-enable this old menu entry
									// in future

/*
	strings
*/
#define NOREGISTER			1
#define NOWINDOW			2
#define UNTITLED			3
#define WARNING				4
#define CLOSE_ANYWAY		5

#define STYLE_SHEETS		10
#define C_SOURCE_FILES		11
#define CG_CONFIG			12
#define CG_LOG				13
#define CONFIG_FILES		14
#define HEADER_FILES		15
#define HELP_PROJECTS		16
#define HTML_FILES			17
#define JAVA_SCRIPTS		18
#define JAVA_FILES			19
#define LIVELINK_FILES		20
#define MAKE_FILES			21
#define DEF_FILES			22
#define BATCH_FILES			23
#define OPL_FILES			24
#define PASCAL_FILES		25
#define PHP_FILES			26
#define PROC_FILES			27
#define PROT_FILES			28
#define REGISTRATION_FILES	29
#define RESSOURCE_FILES		30
#define SQL_SCRIPTS			31
#define SYMBOL_TABLES		32
#define TEXT_FILES			33
#define XML_FILES			34
#define XSD_FILES			35
#define XSL_FILES			36
#define DTD_FILES			37
#define ALL_FILES			38

